

spring:
  # 数据库链接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.52.135:3306/free
    username: root
    password: 123456

  # redis 配置
  redis:
    # 配置数据库，默认为0
    database: 0
    # 链接服务器地址
    host: 192.168.52.135
    # 端口
    port: 6379
    # 服务器链接密码，默认为空
    password:
    # 连接超时时间（毫秒）
    timeout:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  #添加之后，url可以匹配.html .json等后缀
  mvc:
    pathmatch:
      use-suffix-pattern: true

# 配置上下文环境
server:
  servlet:
    # 修改上下文路径
    context-path: /hsiang
  # 修改端口
  port: 7200

# mybatis 配置
mybatis:
  type-aliases-package: com.free.dao.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

# 引入log4j2配置文件
logging:
  config: classpath:log4j2.yml
